version: '3.6'

services:
  web:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
      - python_server
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
  python_server:
    image: python-scanner
  